name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      if: success()
    - name: pack
      run: dotnet pack
    - name: push
      run: cd '/home/runner/work/MicroserviceAuthenticator/MicroserviceAuthenticator/MicroServices.Identity.Authentication/bin/Debug' && dotnet nuget push MicroServiceAuthenticator.1.0.0.nupkg -k oy2pczc7eaqvngosgymqprzxyuilnfaerpbkfi4biuq67a -s https://api.nuget.org/v3/index.json
    
